### ISSUE TITLE
Re-order CMakeLists.txt ISPC detection under PROJECT define

### ISSUE THREAD

**Issue by boberfly** [neilogd/Engine#16]
Hey Neil,

https://github.com/neilogd/Engine/blob/master/CMakeLists.txt#L11
Super-easy fix, if this ISPC stuff could sit under the PROJECT(Engine CXX) line then it'll work fine if I have ISPC outside the Engine directory.

Cheers!

**Comment by neilogd** [comment]
I don't have it setup in the Engine directory at the moment, just in the parent folder and it seems to be fine with that. If reordering does fix it for you then I'm happy to move it though. I'm tempted to get it to parse an environment variable too, since that is a bit more flexible.

Out of curiosity, what folder structure are you using? Mine for example is:

Dev Directory:
-- Engine
-- ispc-v1.9.1-windows-vs2015
-- other misc projects...

**Comment by boberfly** [comment]
Yep that's exactly my set-up after reading the ispc.cmake file, but a lot of the variables it relies on don't get set until the PROJECT(Engine CXX) is invoked so it doesn't find it at all, or know that I'm using VS2015 (falls back to trying to find VS2013 ispc). Funny how you're not getting that problem though, this is a fresh check-out of features/graphics

**Comment by neilogd** [comment]
Done
